import { CALIBRATION, CALIBRATION_VERSION } from "./calibration.js";

export const RECOMMENDATION_POLICY_VERSION = CALIBRATION_VERSION;
export const RECOMMENDATION_POLICY = CALIBRATION.recommendationPolicy;
